### ISSUE TITLE
Placeholders with carriage returns break Quill

### ISSUE THREAD

**Issue by Botje** [brettimus/quill-placeholder#9]
First, thank you for this Quill plugin.
Today we discovered that setting a placeholder with embedded carriage returns breaks Quill.

Example: (See it live at http://jsbin.com/lupukisuwu/1/edit?js,output)

``` javascript
var basicEditor = new Quill('#basic-editor');
basicEditor.addModule('toolbar', {
  container: '#basic-toolbar'
});
basicEditor.addModule('placeholder', { text: "First line\r\nSecond line\r\nThird line" });
```

Expected: Three placeholder-styled lines
Actual: Actual lines in the editor, along with the following error:

```
error TypeError: Cannot read property 'length' of undefined
    at https://cdn.quilljs.com/0.20.1/quill.js:6413:35
    at Selection.shiftAfter (https://cdn.quilljs.com/0.20.1/quill.js:7549:5)
    at Editor._deleteAt (https://cdn.quilljs.com/0.20.1/quill.js:6408:27)
    at https://cdn.quilljs.com/0.20.1/quill.js:6318:28
    at arrayEach (https://cdn.quilljs.com/0.20.1/quill.js:618:11)
    at Function.<anonymous> (https://cdn.quilljs.com/0.20.1/quill.js:1893:11)
    at https://cdn.quilljs.com/0.20.1/quill.js:6310:13
    at Editor._trackDelta (https://cdn.quilljs.com/0.20.1/quill.js:6504:5)
    at Editor.applyDelta (https://cdn.quilljs.com/0.20.1/quill.js:6306:20)
    at Quill.updateContents (https://cdn.quilljs.com/0.20.1/quill.js:10566:24)
```

**Comment by Botje** [comment]
We are aware this module is deprecated now, but Quill 1.0.0 stable is still a ways off and somebody else might come across the same issue.

**Comment by brettimus** [comment]
Thanks for flagging this! I can't guarantee I'll be able to look at it any time soon, but I'll keep the issue open so another intrepid soul might try their hand at it.
